### PR TITLE
Update copyright notice to 2016 [ci skip]

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by zpao** [comment]
Thanks, but we should just make this -present (and we need to update the headers in the other files as well). Want to do that?

**Comment by Atul9** [comment]
I would like to do it. What does 'update the headers' mean?

**Comment by zpao** [comment]
We have license headers in each of the source files that lists the years much like the LICENSE file. https://github.com/facebook/emitter/blob/master/src/BaseEventEmitter.js#L2 is one example.

**Comment by zpao** [comment]
Did this myself while I was in there. aaca11a8653fa104f901c6db24b59cc4b19f98a0

**Pull request closed without merging**
