### PR TITLE
Update fbjs and other npm dependencies for compatibility with React Native

### LINKED ISSUE #13: Update dependencies
Right now it relies on a very old version of fbjs.

### PR DESCRIPTION
**Pull request by ide**
React Native wants there to be only one copy of fbjs, which can be achieved if fbemitter uses fbjs@^0.6.0. This commit updates fbjs and a couple other npm dependencies.

Fixes #13.

### CODE REVIEW

**Comment by kyldvs** [comment]
Looks good to me, thanks!

**Comment by ide** [comment]
Thanks! Could you publish 2.0.1 when you get a chance to?

**Comment by kyldvs** [comment]
Sure! Filed #17 so I don't forget since I will be on PTO for a few more days. Please ping the issue later next week if I've still not got to it :)

Or if you need it sooner perhaps @zpao or someone else can do it real quick

**Comment by zpao** [comment]
This chasing of dependencies so there's a single version of fbjs is going to get tricky and I really don't think it's going to be maintainable. It's fine to do for now but we should talk about a better long term solution (not here though)

**Comment by ide** [comment]
@zpao there's a set of external PRs to fbjs and RN so that RN's packager can properly consume multiple versions of fbjs so I don't think this will be a huge problem moving forward.

Separately, it is important that fbjs follows semver to some degree (ex: publish breaking changes as 0.7.0 instead of 0.6.1) since if npm3 finds fbjs@^0.6.0 and fbjs@^0.6.1 in two different dependencies' package.json files, it will dedupe them and install only fbjs@0.6.1.

**Comment by zpao** [comment]
👍

I've been pretty strict about fbjs following semver so I don't think we should have a problem there. There's always the possibility we screw that up since our API surface area is quite large but hopefully not.

**Pull request merged**
